<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getFrontendLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>
<?php 
		$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
		$product = $objectManager->get('Magento\Framework\Registry')->registry('product');//get current product
		$cates = $product->getCategoryIds();
		//print_r($cates);
?>
<div class="product attribute">
				<strong class="type">Category :</strong>
				<?php $i=0; ?>
				<?php foreach($cates as $c){ ?>
					
						<?php $cata = $objectManager->create("Magento\Catalog\Model\Category")->load($c); ?>
					<?php if($cata->getLevel()==2): ?>
					<span class="value"><?php echo $cata->getName(); ?> </span>
					<?php endif; ?>
				<?php } ?>
				
</div>

<?php if($_attributeValue): ?>
	<?php if($_className == 'overview'): ?>
		<?php if($themeHelper->getStoreConfig('mpanel/product_details/short_description')): ?>
			<div class="product attribute <?php /* @escapeNotVerified */ echo $_className?>">
				<?php if ($_attributeLabel != 'none'): ?><strong class="type"><?php /* @escapeNotVerified */ echo $_attributeLabel?></strong><?php endif; ?>
				<div class="value std" <?php /* @escapeNotVerified */ echo $_attributeAddAttribute;?>><?php /* @escapeNotVerified */ echo $_attributeValue; ?></div>
			</div>
		<?php endif; ?>
	<?php elseif($_className == 'sku'): ?>
		<?php if($themeHelper->getStoreConfig('mpanel/product_details/sku')): ?>
			<div class="product attribute <?php /* @escapeNotVerified */ echo $_className?>">
				<?php if ($_attributeLabel != 'none'): ?><strong class="type"><?php /* @escapeNotVerified */ echo $_attributeLabel?></strong><?php endif; ?>
				<span class="value" <?php /* @escapeNotVerified */ echo $_attributeAddAttribute;?>><?php /* @escapeNotVerified */ echo $_attributeValue; ?></span>
			</div>
		<?php endif; ?>
	<?php else: ?>
		<div class="product attribute <?php /* @escapeNotVerified */ echo $_className?>">
			<?php if ($_attributeLabel != 'none' || $_attributeLabel != __('none')): ?><strong class="type"><?php /* @escapeNotVerified */ echo $_attributeLabel?></strong><?php endif; ?>
			<span class="value" <?php /* @escapeNotVerified */ echo $_attributeAddAttribute;?>><?php /* @escapeNotVerified */ echo $_attributeValue; ?></span>
		</div>
	<?php endif ?>
<?php endif ?>
<div class="product attribute tags">
				<strong class="type">Tags :</strong>
				<?php $i=0; ?>
				<?php foreach($cates as $key => $c){ ?>
					
						<?php $cata = $objectManager->create("Magento\Catalog\Model\Category")->load($c); ?>
						<?php if($cata->getLevel()==3): ?>
							<span class="value"><?php echo $cata->getName(); ?></span><span class="comma">,</span>
						<?php endif;?>
				<?php } ?>
				
</div>
