<?php

$request = $this->getResponseParams();

if(empty($request)) {
	die("Authentication Error: Payment transaction fail.");
}

$objCustomerDetail = $this->getCustomerDetail();
$strCurrencyCode = $this->getBaseCurrencyCode();

$home_url = $block->getUrl();
$channel_response_code = $request['channel_response_code'];
$current_order = $request['order_id'];
$order_id = $request['order_id'];
$transaction_ref = $request['transaction_ref'];

$objCustomerOrderDetail  = $this->getOrderDetails($order_id);
$entityId = $objCustomerOrderDetail->getEntityId();
$floatGrandTotal = $objCustomerOrderDetail->getGrandTotal();
$floatGrandTotal = round($floatGrandTotal,2);
$floatGrandTotal = number_format($floatGrandTotal, 2, '.', ',');
$strCustomerName = '';

if($objCustomerDetail->isLoggedIn()) {
	$strCustomerName = $objCustomerDetail->getCustomer()->getName();
} else {
	$strCustomerName = 'Guest';
}

?>
<div class="col-main">
	<div class="page-title"><h1><?php echo __('Your order has been received') .'  '. __($strCustomerName) . __('.') ?></h1></div>
	<?php if(strcasecmp($channel_response_code, "000") == 0 || strcasecmp($channel_response_code, "00") == 0) {  ?>
		<h2 class="sub-title"><?php echo __('Thank you for your purchase!') ?></h2>
		<p><?php echo __('We have received your payment successfully.') ?></p>
	<?php } ?>

	<?php if(strcasecmp($channel_response_code, "001") == 0) {  ?>
		<h2 class="sub-title"><?php echo __('Thank you for your purchase!') ?></h2>
		<p><?php echo __('Your payment is pending, please make the payment before expiry.') ?></p>
	<?php } ?>

	<p><?php echo __('Your Refrence order ID is:') .' '. __($transaction_ref); ?></p>
	<?php if($objCustomerDetail->isLoggedIn()){ ?>
		<p><?php echo __('Your order ID is:') ?> <a href="<?php echo $home_url;?>sales/order/view/order_id/<?php echo $entityId;?>"><?php echo $order_id;?></a></p>
	<?php } else { ?>
		<p><?php echo __('Your order ID is:')?> <a href="<?php echo $home_url;?>sales/guest/view/order_id/<?php echo $entityId;?>"><?php echo $order_id;?></a></p>
	<?php } ?>
	<p><?php echo __('Your Purchase Amount is:') ?> <?php echo $floatGrandTotal;?>&nbsp;&nbsp;<?php echo __($strCurrencyCode) ?></p>

	<p><?php echo __('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
	<?php if($objCustomerDetail->isLoggedIn()){ ?>
		<p><?php echo __('Click') ?> <a href="<?php echo $home_url;?>sales/order/print/order_id/<?php echo $entityId;?>" onclick="this.target='_blank'"><?php echo __('here to print') ?></a> <?php echo __('a copy of your order confirmation.') ?></p>
	<?php } ?>
	<div class="primary">
		<button type="button" class="action primary continue" title="<?php echo __('Continue Shopping') ?>" onclick="window.location='<?php echo $home_url;?>'"><span><?php echo __('Continue Shopping') ?></span></button>
	</div>
</div>