<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Rma
 */
?>
<?php /** @var \Amasty\Rma\Block\Request\Export $block */
    $_request = $block->getRmaRequest();
?>
<img src="<?= $block->getLogoSrc() ?>" alt="<?= $block->getLogoAlt() ?>" width="220" height="22" class="margin-top30" />

<h3 class="margin-top30"><?= __("RMA Return Info")?></h3>

<table class="am-details">
    <tr>
        <td class="label"><?= __("Date")?></td>
        <td><?= $block->formatDate($_request->getData('created_at'), \IntlDateFormatter::MEDIUM)?></td>
    </tr>
    <tr>
        <td class="label"><?= __("ID")?></td>
        <td><?= $_request->getId()?></td>
    </tr>
    <tr>
        <td class="label"><?= __("Order ID")?></td>
        <td><?= $_request->getData('increment_id')?></td>
    </tr>
    <tr>
        <td class="label"><?= __("Code")?></td>
        <td><?= $_request->getData('code')?></td>
    </tr>
</table>

<table style="width: 100%;" class="margin-top30">
    <tr>
        <th><h3><?= __("Customer Address")?></h3></th>
        <th><h3><?= __("Return Department Address")?></h3></th>
    </tr>
    <tr>
        <td><?= $block->getCustomerAddress();?></td>
        <td><?= $block->getReturnAddress();?></td>
    </tr>
</table>
<div class="block block-orders-info margin-top30">
    <h3 class="block-title--myac"><?= __("Items") ?></h3>
    <div class="table-wrapper orders-history table-responsive">
        <table class="data-table table table-order-items history" id="my-returns-items-table">
            <thead>
            <tr>
                <th><?= __('Product Name') ?></th>
                <th><?= __('SKU') ?></th>
                <th><?= __('Qty') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php /** @var \Amasty\Rma\Model\Item $item */
            foreach ($block->getData('items') as $key => $item): ?>
                <tr>
                    <td><?= $block->escapeHtml($item->getData('name')) ?></td>
                    <td><?= $block->escapeHtml($item->getData('sku')) ?></td>
                    <td><?= $block->escapeHtml($item->getData('qty')); ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<div class="buttons no-print">
    <button type="button" class="action btn btn-xs btn-primary" onclick="window.print()"><?= __("Print") ?></button>
    <button type="button" class="action btn btn-xs btn-secondary" onclick="window.close()"><?= __("Close") ?></button>
</div>
